on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.c16483.nichost.ru
        FTP_USERNAME: c16483_ftp
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        ARGS: --exclude=includes/startup.php --exclude=log/clever.log --exclude=css/clubclever-admin.css --exclude=css/clubclever-theme.css --exclude=css/clubclever.css --exclude=css/search.css --exclude=js/auth-form.js --exclude=js/bootstrap.js --exclude=js/clubclever.js --exclude=js/custom.js --exclude=jquery-editable-select.js --exclude=js/jquery.smartmenus.bootstrap.js 
